In [2]:
from tool1 import *
set_seed(0)

In [3]:
a = torch.zeros(2, 3)
b = torch.ones(2, 3)
c = torch.randn(2, 3)
d = torch.arange(0, 12).reshape(3, 4)
e = torch.linspace(-1, 1, 5)

print('a:', a)
print('b:', b)
print('c:', c)
print('d:', d)
print('e:', e)

a: tensor([[0., 0., 0.],
        [0., 0., 0.]])
b: tensor([[1., 1., 1.],
        [1., 1., 1.]])
c: tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986]])
d: tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
e: tensor([-1.0000, -0.5000,  0.0000,  0.5000,  1.0000])


In [5]:
x = torch.randn(2, 3, 4)
print('shape:', x.shape)
print('ndim', x.ndim)
print('numel:', x.numel())
print('dtype:', x.dtype)
print('device:', x.device)

shape: torch.Size([2, 3, 4])
ndim 3
numel: 24
dtype: torch.float32
device: cpu


# Broadcasting

In [9]:
a = torch.arange(6).reshape(2, 3).float()
b = torch.tensor([10., 20., 30.])
print(a + b)

c = torch.tensor([[100.], [200.]])
print(a + c)

x = torch.tensor([[1.], [2.], [3.]])
y = torch.tensor([[10., 20., 30., 40.]])
print(x + y)

tensor([[10., 21., 32.],
        [13., 24., 35.]])
tensor([[100., 101., 102.],
        [203., 204., 205.]])
tensor([[11., 21., 31., 41.],
        [12., 22., 32., 42.],
        [13., 23., 33., 43.]])


# Indexing / Scicing

In [15]:
x = torch.arange(20).reshape(4, 5)
print(x)
print('row1:', x[1])
print('col1:', x[:, 2]) 
print(x[x > 10])  #  10 이상 값만 뽑기 mask
print(x > 10)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
row1: tensor([5, 6, 7, 8, 9])
col1: tensor([ 2,  7, 12, 17])
tensor([11, 12, 13, 14, 15, 16, 17, 18, 19])
tensor([[False, False, False, False, False],
        [False, False, False, False, False],
        [False,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]])


In [ ]:
# Reshape, View, Contigous
x = torch.arange(12).reshape(3, 4)
y = x.t()

# in memory: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
print(x)
print(y)
print(x.is_contiguous())
print(y.is_contiguous())

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])
True
False


In [ ]:
a = torch.randn(3, 4)
b = torch.randn(4, 5)
print('matmul:', (a @ b).shape)
print('sum dim=0:', a.sum(dim=0).shape)
print('sum dim=1:', a.sum(dim=1).shape)
print('argmax', a.argmax(dim=1))
# max, min, std, unique

matmul: torch.Size([3, 5])
sum dim=0: torch.Size([4])
sum dim=1: torch.Size([3])
argmax tensor([3, 3, 3])
