In [2]:
from tool1 import *
import torch

set_seed(42)
print(torch.__version__)
print('device:', get_device())

2.11.0+cpu
device: cpu


In [3]:
x = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(x)
print('shape:', x.shape, 'dtype:', x.dtype, 'device:', x.device)

tensor([[1., 2.],
        [3., 4.]])
shape: torch.Size([2, 2]) dtype: torch.float32 device: cpu


In [4]:
w = torch.tensor(2.0, requires_grad=True)
x = torch.tensor(3.0)

y = w * x + 1.0
loss = (y - 10.0) ** 2
loss.backward()
print('w.grad:', w.grad.item(), 'excepted:', 2 * (w.item() * x.item() + 1.0 - 10.0) * x.item())

w.grad: -18.0 excepted: -18.0


In [5]:
import numpy as np
arr = np.arange(6).reshape(2, 3).astype('float32')
t = torch.from_numpy(arr)
t2 = t  * 2

print(arr)
print(t)
print(t2)
print(t.data_ptr(), t2.data_ptr() , arr.__array_interface__['data'][0])

[[0. 1. 2.]
 [3. 4. 5.]]
tensor([[0., 1., 2.],
        [3., 4., 5.]])
tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.]])
657893680 747043200 657893680


In [ ]:
device = get_device()
print(device)
x = torch.tensor([1.0, 2.0, 3.0]).to('cpu') # cuda, mps
print(x.device)

cpu
cpu
